### ISSUE TITLE
can you contact me about LNQ 2023 writeups?

### ISSUE THREAD

**Issue by pieper** [WltyBY/LNQ2023_training_code#1]
@WltyBY - I've been trying to reach you by email but haven't heard back, so maybe I have the wrong address.  Can you contact me about publication of your LNQ 2023 MICCAI results?

**Comment by WltyBY** [comment]
I'm sorry there may be some issues with my email. And it's my honor to participate the publication.

**Comment by pieper** [comment]
Excellent!  I found another email for you so hopefully you will receive more details that way.  If you don't get an email contact me at pieper at isomics dot com.
