### ISSUE TITLE
Request for Access to LNQ2023 Dataset for Research

### ISSUE THREAD

**Issue by eclouder** [WltyBY/LNQ2023_training_code#2]
I am currently working on lymph node medical segmentation research. I came across your code related to the LNQ2023 Challenge, which I found very insightful.
I am seeking access to the LNQ2023 dataset, as it contains high-quality annotations that are critical for my work. I applied to join the challenge on Grand-Challenge under the username eclouderfordl but have not yet received approval.
If you have any insights or could share how I might access the dataset, I would greatly appreciate it. Your help would significantly enhance my research efforts.
Thank you for considering my request!

**Comment by WltyBY** [comment]
I'm sorry, I can't provide you with the dataset. If the competition organizer has not approved your application on the competition page, I think it is a good choice to contact the competition organizer on the contact page. Here is the link to the page: https://lnq2023.grand-challenge.org/contact/. 
If the original dataset is useful to you, you can find it on TCIA: https://www.cancerimagingarchive.net/collection/mediastinal-lymph-node-seg/.
